#!/usr/bin/env tsx

/**
 * Generate Local Environment Configuration
 *
 * Outputs the environment variables needed in .env.local for local Supabase development.
 * This script reads from `supabase status` and formats them for .env.local
 *
 * Usage:
 *   tsx scripts/dev/generate-local-env.ts
 *   tsx scripts/dev/generate-local-env.ts > .env.local.supabase
 */

import { exec } from 'child_process'
import { promisify } from 'util'
import { logger } from '../lib/logger'

const execAsync = promisify(exec)

async function generateLocalEnv() {
  logger.start('Generating local environment configuration...')

  try {
    // Get Supabase status in env format
    const { stdout, stderr } = await execAsync('npx supabase status -o env')

    if (stderr && !stderr.includes('Stopped services')) {
      logger.warn('Warning from Supabase:', stderr)
    }

    // Parse the environment variables
    const envVars: Record<string, string> = {}
    stdout.split('\n').forEach((line) => {
      const match = line.match(/^([A-Z_]+)="([^"]+)"$/)
      if (match) {
        envVars[match[1]] = match[2]
      }
    })

    if (!envVars.ANON_KEY || !envVars.SERVICE_ROLE_KEY || !envVars.API_URL) {
      throw new Error('Failed to parse Supabase configuration. Is Supabase running? (npm run db:start)')
    }

    // Generate .env.local content
    logger.section('Local Supabase Configuration')
    console.log('# Supabase Local Development Configuration')
    console.log('# Generated by: tsx scripts/dev/generate-local-env.ts')
    console.log('# ')
    console.log('# To use this:')
    console.log('# 1. Copy the lines below')
    console.log('# 2. Replace the Supabase section in your .env.local')
    console.log('# 3. Keep your other env vars (AI_MODE, ANTHROPIC_API_KEY, etc.)')
    console.log('')
    console.log('# Supabase Configuration (Local Development)')
    console.log(`NEXT_PUBLIC_SUPABASE_URL=${envVars.API_URL}`)
    console.log(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.ANON_KEY}`)
    console.log(`SUPABASE_SERVICE_ROLE_KEY=${envVars.SERVICE_ROLE_KEY}`)
    console.log('')

    logger.complete('Configuration generated successfully!')
    logger.info('')
    logger.info('Next steps:')
    logger.info('1. Copy the configuration above')
    logger.info('2. Update the Supabase section in your .env.local')
    logger.info('3. Run: npm run seed:users')
    logger.info('')
    logger.info('Tip: To save directly to a file:')
    logger.info('  tsx scripts/dev/generate-local-env.ts > .env.local.supabase')
  } catch (error) {
    logger.error('Failed to generate configuration:', error)
    logger.info('')
    logger.info('Make sure Supabase is running:')
    logger.info('  npm run db:start')
    logger.info('  npm run db:status')
    process.exit(1)
  }
}

generateLocalEnv()
